name: /dshare/home/lidb/miniconda3/envs/Qnorm
channels:
- conda-forge
- bioconda
dependencies:
- r-base=4.4.2
- r-dplyr=1.1.4
- r-ggridges=0.5.6
- r-ggplot2=3.5.2
- r-data.table=1.17.8
- r-ggpmisc=0.6.2
- r-viridis=0.6.5
- bioconductor-genomicranges=1.58.0
- bioconductor-preprocesscore=1.68.0
- r-ggpointdensity=0.2.0
- bioconductor-bsgenome.mmusculus.ucsc.mm10=1.4.3
- r-plotly=4.11.0
- bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.5
- r-tidyr=1.3.1
- r-gridextra=2.3